AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda application for refining Tempest weather observations.
Parameters:
  TempestHost:
    Type: String
    Description: Host for the Tempest API
  TempestToken:
    Type: String
    Description: Token for the Tempest API
  TempestDeviceId:
    Type: String
    Description: Device ID for the Tempest API
  TempestStationId:
    Type: String
    Description: Station ID for the Tempest API
Resources:
  TempestS3AccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Tempest weather app access to S3 resources for observation refinement.
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - s3:ListBucket
            Effect: Allow
            Resource:
              - !Sub "arn:aws:s3:::weather-tempest-records"
          - Action:
              - s3:GetObject
              - s3:PutObject
              - s3:AbortMultipartUpload
              - s3:ListBucketMultipartUploads
              - s3:ListMultipartUploadParts
            Effect: Allow
            Resource:
              - !Sub "arn:aws:s3:::weather-tempest-records/*"
  TempestAthenaGlueAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Tempest weather app access to Athena and Glue resources for refinement.
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - athena:StartQueryExecution
              - athena:GetQueryExecution
              - athena:GetQueryResults
            Effect: Allow
            Resource: "*"
          - Action:
              - glue:GetDatabase
              - glue:GetDatabases
              - glue:GetTable
              - glue:GetTables
              - glue:GetPartition
              - glue:GetPartitions
              - glue:CreateTable
              - glue:UpdateTable
              - glue:BatchCreatePartition
              - glue:CreatePartition
            Effect: Allow
            Resource: "*"
  TempestLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs24.x
      CodeUri: function/.
      Description: Refine Tempest weather observations.
      MemorySize: 1024
      Timeout: 60
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - !Ref TempestS3AccessPolicy
        - !Ref TempestAthenaGlueAccessPolicy
      Tracing: Active
      Layers:
        - !Ref TempestLambdaDependencies
      Events:
        TempestRefineSchedule:
          Type: Schedule
          Properties:
            Description: Invoke the refinement Lambda every day at 05:00 UTC.
            Schedule: "cron(0 5 * * ? *)"
            Enabled: true
      Environment:
        Variables:
          TEMPEST_HOST: !Ref TempestHost
          TEMPEST_TOKEN: !Ref TempestToken
          TEMPEST_DEVICE_ID: !Ref TempestDeviceId
          TEMPEST_STATION_ID: !Ref TempestStationId
  TempestLambdaDependencies:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: tempest-weather-refine-lib
      Description: Dependencies for the Tempest weather observations REFINER app.
      ContentUri: ../../lib/.
      CompatibleRuntimes:
        - nodejs24.x
