AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Parameters:
  TempestHost:
    Type: String
    Description: Host for the Tempest API
  TempestToken:
    Type: String
    Description: Token for the Tempest API
  TempestDeviceId:
    Type: String
    Description: Device ID for the Tempest API
  TempestStationId:
    Type: String
    Description: Station ID for the Tempest API
  AlertEmail:
    Type: String
    Default: ''
    Description: Optional email endpoint for CloudWatch alarm notifications.
Conditions:
  HasAlertEmail: !Not [!Equals [!Ref AlertEmail, '']]
Resources:
  AlertsTopic:
    Type: AWS::SNS::Topic
    Condition: HasAlertEmail
    Properties:
      TopicName: !Sub "${AWS::StackName}-alerts"
  AlertsTopicSubscription:
    Type: AWS::SNS::Subscription
    Condition: HasAlertEmail
    Properties:
      Protocol: email
      TopicArn: !Ref AlertsTopic
      Endpoint: !Ref AlertEmail
  AlertsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Condition: HasAlertEmail
    Properties:
      Topics:
        - !Ref AlertsTopic
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudwatch.amazonaws.com
            Action: sns:Publish
            Resource: !Ref AlertsTopic
  TempestS3AccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Tempest weather app access to s3 resources"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - s3:ListBucket
            Effect: Allow
            Resource: "*"
          - Action:
            - s3:PutObject
            - s3:GetBucketLocation
            - s3:GetObject
            - s3:ListBucketMultipartUploads
            - s3:ListMultipartUploadParts
            - s3:AbortMultipartUpload
            - s3:PutObject
            Effect: Allow
            Resource:
            - !Sub "arn:aws:s3:::weather-tempest-records/*"
            - !Sub "arn:aws:s3:::weather-tempest-records"
          - Action: athena:*
            Effect: Allow
            Resource: "*"
          - Action:
              - glue:CreateDatabase
              - glue:DeleteDatabase
              - glue:GetDatabase
              - glue:GetDatabases
              - glue:UpdateDatabase
              - glue:CreateTable
              - glue:DeleteTable
              - glue:BatchDeleteTable
              - glue:UpdateTable
              - glue:GetTable
              - glue:GetTables
              - glue:BatchCreatePartition
              - glue:CreatePartition
              - glue:DeletePartition
              - glue:BatchDeletePartition
              - glue:UpdatePartition
              - glue:GetPartition
              - glue:GetPartitions
              - glue:BatchGetPartition
            Effect: Allow
            Resource:
              - "*"
  TempestLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs24.x
      CodeUri: function/.
      Description: Read the Tempest weather observations.
      MemorySize: 1024
      Timeout: 60
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - !Ref TempestS3AccessPolicy
      Tracing: Active
      Layers:
        - !Ref TempestLambdaDependencies
      Environment:
        Variables:
          TEMPEST_HOST: !Ref TempestHost
          TEMPEST_TOKEN: !Ref TempestToken
          TEMPEST_DEVICE_ID: !Ref TempestDeviceId
          TEMPEST_STATION_ID: !Ref TempestStationId
          ATHENA_WORKGROUP: !Ref TempestAthenaWorkGroup
          QUERY_TIMEOUT_MS: "25000"
          QUERY_TIMEOUT_SAFETY_BUFFER_MS: "5000"
  TempestAthenaWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: !Sub "${AWS::StackName}-fetch-observations"
      Description: Bounded Athena workgroup for fetch-observations API queries.
      RecursiveDeleteOption: true
      State: ENABLED
      WorkGroupConfiguration:
        EnforceWorkGroupConfiguration: true
        PublishCloudWatchMetricsEnabled: true
        BytesScannedCutoffPerQuery: 500000000
        ResultConfiguration:
          OutputLocation: "s3://weather-tempest-records/queries/"
          EncryptionConfiguration:
            EncryptionOption: SSE_S3
  TempestLambdaDependencies:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: tempest-weather-read-lib
      Description: Dependencies for the Tempest weather observations READ app.
      ContentUri: ../../lib/.
      CompatibleRuntimes:
        - nodejs24.x
  TempestDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref 'AWS::AccountId'
      DatabaseInput:
        Description: Tempest observations database
        Name: tempest_weather
  TempestGlue:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref 'AWS::AccountId'
      DatabaseName: !Ref TempestDatabase
      TableInput:
        Name: "observations"
        TableType: "EXTERNAL_TABLE"
        Parameters:
          EXTERNAL: "TRUE"
        StorageDescriptor:
          Columns:
            - Name: "deviceid"
              Type: "int"
            - Name: "datetime"
              Type: "int"
            - Name: "windlull"
              Type: "int"
            - Name: "windavg"
              Type: "int"
            - Name: "windgust"
              Type: "int"
            - Name: "winddirection"
              Type: "int"
            - Name: "windsampleinterval"
              Type: "int"
            - Name: "pressure"
              Type: "int"
            - Name: "airtemperature"
              Type: "int"
            - Name: "relativehumidity"
              Type: "int"
            - Name: "illuminance"
              Type: "int"
            - Name: "uv"
              Type: "int"
            - Name: "solarradiation"
              Type: "int"
            - Name: "rainaccumulation"
              Type: "int"
            - Name: "precipitationtype"
              Type: "int"
            - Name: "avgstrikedistance"
              Type: "int"
            - Name: "strikecount"
              Type: "int"
            - Name: "battery"
              Type: "int"
            - Name: "reportinterval"
              Type: "int"
            - Name: "localdayrainaccumulation"
              Type: "int"
            - Name: "ncrainaccumulation"
              Type: "int"
            - Name: "localdayncrainaccumulation"
              Type: "int"
            - Name: "precipitationanalysis"
              Type: "int"
          Location: "s3://weather-tempest-records/"
          InputFormat: "org.apache.hadoop.mapred.TextInputFormat"
          OutputFormat: "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
          Compressed: false
          NumberOfBuckets: -1
          SerdeInfo:
            SerializationLibrary: "org.apache.hive.hcatalog.data.JsonSerDe"
            Parameters:
              serialization.format: "1"
          BucketColumns: [ ]
          SortColumns: [ ]
          Parameters: { }
          SkewedInfo:
            SkewedColumnNames: [ ]
            SkewedColumnValues: [ ]
            SkewedColumnValueLocationMaps: { }
          StoredAsSubDirectories: false
        PartitionKeys:
          - Name: "year"
            Type: "string"
          - Name: "month"
            Type: "string"
          - Name: "day"
            Type: "string"
          - Name: "hour"
            Type: "string"
  FunctionURLAllowPublicAccess:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunctionUrl
      FunctionName: !Ref TempestLambdaFunction
      FunctionUrlAuthType: NONE
      Principal: "*"
  FunctionURLInvokeAllowInvokeAction:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref TempestLambdaFunction
      Principal: "*"
  LambdaFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      InvokeMode: BUFFERED
      TargetFunctionArn: !Ref TempestLambdaFunction
  TempestLambdaErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: HasAlertEmail
    Properties:
      AlarmDescription: !Sub "Lambda ${TempestLambdaFunction} reported errors."
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref TempestLambdaFunction
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertsTopic
  TempestLambdaThrottlesAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: HasAlertEmail
    Properties:
      AlarmDescription: !Sub "Lambda ${TempestLambdaFunction} reported throttles."
      Namespace: AWS/Lambda
      MetricName: Throttles
      Dimensions:
        - Name: FunctionName
          Value: !Ref TempestLambdaFunction
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertsTopic
  TempestLambdaDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: HasAlertEmail
    Properties:
      AlarmDescription: !Sub "Lambda ${TempestLambdaFunction} duration exceeded 48s."
      Namespace: AWS/Lambda
      MetricName: Duration
      Dimensions:
        - Name: FunctionName
          Value: !Ref TempestLambdaFunction
      Statistic: Maximum
      Period: 300
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 48000
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertsTopic
Outputs:
  AlertsTopicArn:
    Condition: HasAlertEmail
    Value: !Ref AlertsTopic
