AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: One-off backfill workflow to register historical S3 partitions in Athena.

Parameters:
  BackfillBucket:
    Type: String
    Default: weather-tempest-records
    Description: Bucket containing historical observation records and where manifests/chunks are written.
  BackfillScanPrefix:
    Type: String
    Default: ''
    Description: Optional S3 prefix to limit the scan scope.
  BackfillOutputPrefix:
    Type: String
    Default: backfill/athena-partitions
    Description: Prefix where run manifests and partition chunks are stored.
  AthenaDatabase:
    Type: String
    Default: tempest_weather
  AthenaTable:
    Type: String
    Default: observations
  AthenaOutputLocation:
    Type: String
    Default: s3://weather-tempest-records/queries/
  AthenaWorkGroup:
    Type: String
    Default: primary
  ChunkSize:
    Type: Number
    Default: 100
  AlertEmail:
    Type: String
    Default: ''
    Description: Optional email endpoint for CloudWatch alarm notifications.
Conditions:
  HasAlertEmail: !Not [!Equals [!Ref AlertEmail, '']]

Resources:
  AlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${AWS::StackName}-alerts"
  AlertsTopicSubscription:
    Type: AWS::SNS::Subscription
    Condition: HasAlertEmail
    Properties:
      Protocol: email
      TopicArn: !Ref AlertsTopic
      Endpoint: !Ref AlertEmail
  AlertsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref AlertsTopic
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudwatch.amazonaws.com
                - events.amazonaws.com
            Action: sns:Publish
            Resource: !Ref AlertsTopic
  BackfillPlannerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs24.x
      Handler: planner.handler
      CodeUri: function/.
      Timeout: 900
      MemorySize: 512
      Environment:
        Variables:
          BACKFILL_BUCKET: !Ref BackfillBucket
          BACKFILL_SCAN_PREFIX: !Ref BackfillScanPrefix
          BACKFILL_OUTPUT_PREFIX: !Ref BackfillOutputPrefix
          BACKFILL_CHUNK_SIZE: !Ref ChunkSize
          BACKFILL_ATHENA_DATABASE: !Ref AthenaDatabase
          BACKFILL_ATHENA_TABLE: !Ref AthenaTable
          BACKFILL_ATHENA_OUTPUT: !Ref AthenaOutputLocation
          BACKFILL_ATHENA_WORKGROUP: !Ref AthenaWorkGroup
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource: !Sub arn:aws:s3:::${BackfillBucket}
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource: !Sub arn:aws:s3:::${BackfillBucket}/*
  BackfillWorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs24.x
      Handler: worker.handler
      CodeUri: function/.
      Timeout: 900
      MemorySize: 1024
      Environment:
        Variables:
          BACKFILL_ATHENA_DATABASE: !Ref AthenaDatabase
          BACKFILL_ATHENA_TABLE: !Ref AthenaTable
          BACKFILL_ATHENA_OUTPUT: !Ref AthenaOutputLocation
          BACKFILL_ATHENA_WORKGROUP: !Ref AthenaWorkGroup
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: !Sub arn:aws:s3:::${BackfillBucket}/*
            - Effect: Allow
              Action:
                - s3:GetBucketLocation
                - s3:ListBucket
                - s3:ListBucketMultipartUploads
              Resource: !Sub arn:aws:s3:::${BackfillBucket}
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:PutObjectAcl
                - s3:GetObject
                - s3:AbortMultipartUpload
                - s3:ListMultipartUploadParts
              Resource: !Sub arn:aws:s3:::${BackfillBucket}/queries/*
            - Effect: Allow
              Action:
                - athena:StartQueryExecution
                - athena:GetQueryExecution
              Resource: '*'
            - Effect: Allow
              Action:
                - glue:GetDatabase
                - glue:GetDatabases
                - glue:GetTable
                - glue:GetTables
                - glue:GetPartition
                - glue:GetPartitions
                - glue:CreatePartition
                - glue:BatchCreatePartition
              Resource: '*'
  BackfillSummarizeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs24.x
      Handler: summarize.handler
      CodeUri: function/.
      Timeout: 60
      MemorySize: 256
      Policies:
        - AWSLambdaBasicExecutionRole
  BackfillStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: STANDARD
      Definition:
        Comment: Backfill historical S3 partition metadata into Athena.
        StartAt: EnsureMaxConcurrency
        States:
          EnsureMaxConcurrency:
            Type: Choice
            Choices:
              - Variable: $.maxConcurrency
                IsPresent: true
                Next: DetermineChunkSource
            Default: SetDefaultMaxConcurrency
          SetDefaultMaxConcurrency:
            Type: Pass
            Result: 3
            ResultPath: $.maxConcurrency
            Next: DetermineChunkSource
          DetermineChunkSource:
            Type: Choice
            Choices:
              - Variable: $.chunkKeys[0]
                IsPresent: true
                Next: ProcessChunks
            Default: RunPlanner
          RunPlanner:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            OutputPath: $.Payload
            Parameters:
              FunctionName: !GetAtt BackfillPlannerFunction.Arn
              Payload:
                bucket.$: $.bucket
                prefix.$: $.prefix
                outputPrefix.$: $.outputPrefix
                chunkSize.$: $.chunkSize
                maxConcurrency.$: $.maxConcurrency
            Next: EnsureMaxConcurrency
          ProcessChunks:
            Type: Map
            ItemsPath: $.chunkKeys
            ResultPath: $.chunkResults
            MaxConcurrencyPath: $.maxConcurrency
            ItemSelector:
              chunkKey.$: $$.Map.Item.Value
              bucket.$: $.bucket
              database.$: $.database
              table.$: $.table
              outputLocation.$: $.outputLocation
              workGroup.$: $.workGroup
            ItemProcessor:
              StartAt: RunWorker
              States:
                RunWorker:
                  Type: Task
                  Resource: arn:aws:states:::lambda:invoke
                  OutputPath: $.Payload
                  Parameters:
                    FunctionName: !GetAtt BackfillWorkerFunction.Arn
                    Payload:
                      bucket.$: $.bucket
                      chunkKey.$: $.chunkKey
                      database.$: $.database
                      table.$: $.table
                      outputLocation.$: $.outputLocation
                      workGroup.$: $.workGroup
                  Next: ChunkSucceeded
                  Catch:
                    - ErrorEquals:
                        - States.ALL
                      ResultPath: $.error
                      Next: ChunkFailed
                ChunkSucceeded:
                  Type: Pass
                  Parameters:
                    success: true
                    chunkKey.$: $.chunkKey
                    result.$: $
                  End: true
                ChunkFailed:
                  Type: Pass
                  Parameters:
                    success: false
                    chunkKey.$: $.chunkKey
                    error.$: $.error
                  End: true
            Next: SummarizeResults
          SummarizeResults:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            OutputPath: $.Payload
            Parameters:
              FunctionName: !GetAtt BackfillSummarizeFunction.Arn
              Payload:
                chunkResults.$: $.chunkResults
            Next: CheckSummaryFailures
          CheckSummaryFailures:
            Type: Choice
            Choices:
              - Variable: $.failedChunks
                NumericGreaterThan: 0
                Next: BackfillFailed
            Default: Done
          BackfillFailed:
            Type: Fail
            Error: BackfillChunkFailures
            Cause: Backfill execution completed with failed chunks.
          Done:
            Type: Succeed
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref BackfillPlannerFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref BackfillWorkerFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref BackfillSummarizeFunction
  BackfillExecutionStatusEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Notify when backfill execution fails, times out, or is aborted.
      EventPattern:
        source:
          - aws.states
        detail-type:
          - Step Functions Execution Status Change
        detail:
          status:
            - FAILED
            - TIMED_OUT
            - ABORTED
          stateMachineArn:
            - !Ref BackfillStateMachine
      Targets:
        - Arn: !Ref AlertsTopic
          Id: BackfillExecutionStatusAlertTarget
  BackfillPlannerErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: !Sub "Lambda ${BackfillPlannerFunction} reported errors."
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref BackfillPlannerFunction
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertsTopic
  BackfillWorkerErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: !Sub "Lambda ${BackfillWorkerFunction} reported errors."
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref BackfillWorkerFunction
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertsTopic
  BackfillSummarizeErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: !Sub "Lambda ${BackfillSummarizeFunction} reported errors."
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref BackfillSummarizeFunction
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertsTopic
  BackfillWorkerThrottlesAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: !Sub "Lambda ${BackfillWorkerFunction} reported throttles."
      Namespace: AWS/Lambda
      MetricName: Throttles
      Dimensions:
        - Name: FunctionName
          Value: !Ref BackfillWorkerFunction
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertsTopic
  BackfillExecutionsFailedAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Backfill Step Functions execution failed.
      Namespace: AWS/States
      MetricName: ExecutionsFailed
      Dimensions:
        - Name: StateMachineArn
          Value: !Ref BackfillStateMachine
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertsTopic
  BackfillExecutionsTimedOutAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Backfill Step Functions execution timed out.
      Namespace: AWS/States
      MetricName: ExecutionsTimedOut
      Dimensions:
        - Name: StateMachineArn
          Value: !Ref BackfillStateMachine
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertsTopic
  BackfillExecutionsAbortedAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Backfill Step Functions execution aborted.
      Namespace: AWS/States
      MetricName: ExecutionsAborted
      Dimensions:
        - Name: StateMachineArn
          Value: !Ref BackfillStateMachine
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertsTopic

Outputs:
  AlertsTopicArn:
    Value: !Ref AlertsTopic
  BackfillStateMachineArn:
    Value: !Ref BackfillStateMachine
  BackfillPlannerFunctionArn:
    Value: !GetAtt BackfillPlannerFunction.Arn
  BackfillWorkerFunctionArn:
    Value: !GetAtt BackfillWorkerFunction.Arn
  BackfillSummarizeFunctionArn:
    Value: !GetAtt BackfillSummarizeFunction.Arn
